//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalgaryWaterAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.RainFalls = new HashSet<RainFall>();
            this.SnowFalls = new HashSet<SnowFall>();
            this.WaterLevels = new HashSet<WaterLevel>();
            this.Weathers = new HashSet<Weather>();
        }
    
        public string StationCode { get; set; }
        public Nullable<float> Long { get; set; }
        public Nullable<float> Lat { get; set; }
        public string Name { get; set; }
        public Nullable<int> Elevation { get; set; }
        public Nullable<int> StationTypeID { get; set; }
        public Nullable<double> DrainageArea { get; set; }
    
        public virtual ICollection<RainFall> RainFalls { get; set; }
        public virtual ICollection<SnowFall> SnowFalls { get; set; }
        public virtual StationType StationType { get; set; }
        public virtual ICollection<WaterLevel> WaterLevels { get; set; }
        public virtual ICollection<Weather> Weathers { get; set; }
    }
}
