//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalgaryWaterAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationType
    {
        public StationType()
        {
            this.Stations = new HashSet<Station>();
        }
    
        public int ID { get; set; }
        public string Caption { get; set; }
    
        public virtual ICollection<Station> Stations { get; set; }
    }
}
